CREATE TABLE USERS {

    ID INTEGER AUTO_INCREMENT NOT NULL,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASHED VARCHAR(100) NOT NULL,

    PRIMARY KEY ID
}

CREATE INDEX I_USERS_USERNAME ON USERS(USERNAME);

CREATE TABLE ROLES {

    ID INTEGER AUTO_INCREMENT NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    ROLE VARCHAR(100) NOT NULL,

    PRIMARY KEY ID,
    FOREIGN KEY USERNAME ON USERS(USERNAME)
}

CREATE INDEX I_ROLES_USERNAME ON ROLES(USERNAME); -- helps make the database faster
